/**
 * A TaskEvent is an event that is generated by tasks ({@link ExecutionTask}) to
 * signal that a relevant change in the status of a task has taken place.
 * 
 
 * 
 */

using System;

namespace DisciplineOak.Execution.Core.Events
{
	public class TaskEvent : EventArgs
	{
		/** The new status of the task. */
		private readonly ExecutionTask _source;
		private readonly Status _newStatus;
		/** The previous status of the task. */
		private readonly Status _previousStatus;

		/**
	 * Creates a TaskEvent with a particular ExcutionTask as source of the
	 * event. The source (<code>source</code>) is the task whose status has
	 * changed, and <code>newStatus</code> is the new status of the task.
	 * 
	 * @param source
	 *            the task whose status has changed.
	 * @param newStatus
	 *            the new status of the task.
	 */

		public TaskEvent(ExecutionTask source, Status newStatus, Status previousStatus)
		{
			_source = source;
			_newStatus = newStatus;
			_previousStatus = previousStatus;
		}

		/**
	 * Returns the new status associated to the task.
	 * 
	 * @return the new status associated to the task.
	 */

		public Status getNewStatus()
		{
			return _newStatus;
		}

		/**
	 * Returns the previous status associated to the task.
	 * 
	 * @return the previous status associated to the task.
	 */

		public Status getPreviousStatus()
		{
			return _previousStatus;
		}
	}
}